name: Populate Github repository from Salesforce org

# Salesforce login parameters.
# Login with :
# - OBSOLETE : either salesforce_url, salesforce_username, salesforce_password and salesforce_security_token
# - OBSOLETE : or salesforce_url, salesforce_username, salesforce_password without salesforce_security_token
# - OBSOLETE : or salesforce_sfdx_auth_url (get this with : sfdx force:org:display -u bprofilers-prod --verbose)
# - or JWT : salesforce_url, salesforce_username, client_id, private_key
# - (tbc : or with salesforce_accesstoken)

inputs:
  salesforce_url:
    description: Salesforce org url (best with mydomain.my.salesforce.com, mydomain-dev-ed.my.salesforce ou mydomain--mysandbvox.my.salesforce.com
    required: false
  salesforce_username:
    description: Salesforce org admin username
    required: false
  # salesforce_password:
  #   description: Salesforce org admin password
  #   required: false
  # salesforce_security_token:
  #   description: Salesforce security toker
  #   required: false
  # salesforce_sfdx_auth_url:
  #   description: Salesforce SFDX auth URL
  #   required: false
  client_id:
    description: Client ID (consumer key) of the Salesforce connected App
    required: false
  private_key:
    description: Private JWT key used to authenticate the Salesforce connected app
    required: false

  folder_to_commit:
    description: Which folder should we commit to Git, default being .
    default: .
    required: false
  do_git_add:
    description: Do you want to git add ?
    default: false
    required: false
  do_git_commit:
    description: Do you want to git commit ?
    default: false
    required: false
  package_xml:
    description: package.xml manifest file to use for checkout. Optional; if absent, the action retrieves metadata with '--fromorg' option.
    required: false
  timeout:
    description: timeout duration (nb minutes, default 60) passed to the sfdx force:source:retrieve command
    default: 60
    required: false

runs:
  using: "composite"
  steps:
    - name: Retrieve source from Salesforce organization without input package.xml
      uses: RupertBarrow/actions/action-command@v4
      if: ${{ ! inputs.package_xml }}
      with:
        salesforce_url: ${{ inputs.salesforce_url }}
        salesforce_username: ${{ inputs.salesforce_username }}
        client_id: ${{ inputs.client_id }}
        private_key: ${{ inputs.private_key }}
        command: set -x && sfdx project generate manifest --from-org=checkout --output-dir manifest --name package-snapshot-fromorg.xml && sfdx project retrieve start --manifest manifest/package-snapshot-fromorg.xml --wait ${{ inputs.timeout }}

    - name: Retrieve source from Salesforce organization with input package.xml
      uses: RupertBarrow/actions/action-command@v4
      if: ${{ inputs.package_xml }}
      with:
        salesforce_url: ${{ inputs.salesforce_url }}
        salesforce_username: ${{ inputs.salesforce_username }}
        client_id: ${{ inputs.client_id }}
        private_key: ${{ inputs.private_key }}
        #command: sfdx force:source:retrieve -x ${{ inputs.package_xml }}  -w ${{ inputs.timeout }}
        command: set -x && sfdx project retrieve start --manifest ${{ inputs.package_xml }} --wait ${{ inputs.timeout }}

    - name: Prettify code
      shell: bash
      run: |
        set -x
        npm install --save-dev prettier prettier-plugin-sf-xml
        (./node_modules/.bin/prettier --write 'force-app/**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}') || true
        echo "##### Prettify - done #####"

    - name: Configure git settings
      shell: bash
      run: |
        set -x
        git config --global --add safe.directory `pwd`
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: git add ?
      shell: bash
      run: |
        set -x
        ( ${{ inputs.do_git_add }} && git add ${{ inputs.folder_to_commit }} )  || true
        echo "##### git add - done #####"

    - name: git commit ?
      shell: bash
      run: |
        set -x
        ( ${{ inputs.do_git_commit }} && git commit -m "Updated from Salesforce" )  || true
        echo "##### git commit - done #####"
