name: Run Flow
description: 'Execute a named Cumulus flow'
inputs:
  org-name:
    description: 'Name of the scratch org or persistent org config to use'
    required: true
  flow-name:
    description: 'Name of the Cumulus flow to execute'
    required: true
  flow-task-options:
    description: 'Task options passed to the flow (ex \'-o __task__option value\')'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Run Flow (with options)
      env:
        CUMULUSCI_SERVICE_github: '{"username": "${{ github.actor }}", "token": "${{ github.token }}", "email": "cci@github.actions" }'
      run: |
        cci flow run ${{ inputs.flow-name }} --org ${{ inputs.org-name }} ${{ inputs.flow-task-options }} | tee cumulusci-flow.log
      shell: bash
